### ISSUE TITLE
What software the diagrams in your document are made of?

### ISSUE THREAD

**Issue by TenviLi** [rsms/web-clipboard-promise#1]
I found your project in many projects, which gave me a lot of inspiration about the use of clipboard API.

When I look through your [document](https://rsms.me/web-clipboard-promise/), I see the diagram of the implementation method below.

These diagrams are so beautiful.

May I ask you what software the diagrams in your document are made of? Thank you

![](https://rsms.me/web-clipboard-promise/about-3.svg?v2)

**Comment by TenviLi** [comment]
maybe the MacOS APP `OmniGraffle`?

**Comment by rsms** [comment]
[Figma](https://figma.com) :–)

**Comment by TenviLi** [comment]
@rsms thanq!
